spring:
  datasource:
    data: data.sql
    driver-class-name: org.postgresql.Driver
    url: #jdbc:postgresql://ec2-54-217-214-201.eu-west-1.compute.amazonaws.com:5432/dc....
    username: #z
    password: #0

  jpa:
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL82Dialect
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
        # Fix Postgres JPA Error:
        # Method org.postgresql.jdbc.PgConnection.createClob() is not yet implemented.
        temp.use_jdbc_metadata_defaults: false

  # Mustache template
  mustache:
    charset: UTF-8