spring:
  datasource:
    data: data.sql
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgres://dpcwdmmygwvxqe:d113638b455977377844724fea4f9e7aac7ff8dbc4685516ecbdd25d5b52a39b@ec2-54-246-86-167.eu-west-1.compute.amazonaws.com:5432/darsad67es2t64
    username: dpcwdmmygwvxqe
    password: d113638b455977377844724fea4f9e7aac7ff8dbc4685516ecbdd25d5b52a39b

  jpa:
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL82Dialect
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
        # Fix Postgres JPA Error:
        # Method org.postgresql.jdbc.PgConnection.createClob() is not yet implemented.
        temp.use_jdbc_metadata_defaults: false

  # Mustache template
  mustache:
    charset: UTF-8